### ISSUE TITLE
Time For Salah Website is down

### ISSUE THREAD

**Issue by damascene** [AbdulMalikDev/TimeForSalahWebsite#1]
السلام عليكم
I've tried to access the website to check one calculation method but I found it's currently down.
Could you please restore it or provide alternative link?

**Comment by AbdulMalikDev** [comment]
It's working for me.

Can u provide a screenshot ?

https://www.timeforsalah.com/day

**Comment by damascene** [comment]
![image](https://user-images.githubusercontent.com/411046/87847068-93219280-c8dd-11ea-9142-dd78a3f97dee.png)
it's working sometimes, not always. most of the time it doesn't open at all.
here you can see load time is 30s
![image](https://user-images.githubusercontent.com/411046/87847091-c82de500-c8dd-11ea-96b0-0789bfd0a97a.png)

**Comment by AbdulMalikDev** [comment]
oh that's bad. Is it possible for you to send a PR? i'm busy with other projects for now.

**Comment by damascene** [comment]
Is it a code related issues or a hosting issue? It's mentioning something about checking the logs. Unfortunately I'm not a coder but if you can direct me toward the exact issue I might be able to ask someone.

**Comment by AbdulMalikDev** [comment]
The hosting issue might be linked to Heroku. I'm hosting the site on Heroku since its free.
